# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [2]:
lista = ["TNF-alpha", "IL-6", "BRCA1","LAMB3","HDAC1"]
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])
print(lista[4])

TNF-alpha
IL-6
BRCA1
LAMB3
HDAC1

In [3]:
lista_TNF_alpha = [
    len(lista [0]),
    lista[0][:2],
    lista[0].count("a"),
    "hu" in lista [0]
]
print(lista_TNF_alpha)

[9, 'TN', 2, False]

In [4]:
lista_IL6 = [
     len(lista [1]),
    lista[1][:2],
    lista[1].count("a"),
    "hu" in lista [1]
]
print(lista_IL6)

[4, 'IL', 0, False]

In [5]:
lista_BRCA1 = [
     len(lista [2]),
    lista[2][:2],
    lista[2].count("a"),
    "hu" in lista [2]
]
print(lista_BRCA1)

[5, 'BR', 0, False]

In [6]:
lista_LAMB3 = [
     len(lista [3]),
    lista[3][:2],
    lista[3].count("a"),
    "hu" in lista [3]
]
print(lista_LAMB3)

[5, 'LA', 0, False]

In [7]:
lista_HDAC1 = [
     len(lista [4]),
    lista[4][:2],
    lista[4].count("a"),
    "hu" in lista [4]
]
print(lista_HDAC1)

[5, 'HD', 0, False]

In [8]:
matriz = [lista_TNF_alpha, lista_IL6, lista_BRCA1, lista_LAMB3, lista_HDAC1]
matriz

[[9, 'TN', 2, False],
 [4, 'IL', 0, False],
 [5, 'BR', 0, False],
 [5, 'LA', 0, False],
 [5, 'HD', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [9]:
import numpy as np

In [10]:
array_genes = np.array(matriz)
array_genes

array([['9', 'TN', '2', 'False'],
       ['4', 'IL', '0', 'False'],
       ['5', 'BR', '0', 'False'],
       ['5', 'LA', '0', 'False'],
       ['5', 'HD', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [11]:
array_genes[2]

array(['5', 'BR', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [12]:
array_genes[:, -1]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [13]:
array_genes[1, 1:3]

array(['IL', '0'], dtype='<U21')

In [14]:
array_genes[3, 1:3]

array(['LA', '0'], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [15]:
import pandas as pd

In [16]:
lista_final = {lista [0]: lista_TNF_alpha,
               lista [1]: lista_IL6,
               lista [2]: lista_BRCA1,
               lista [3]: lista_LAMB3,
               lista [4]: lista_HDAC1}
lista_final

{'TNF-alpha': [9, 'TN', 2, False],
 'IL-6': [4, 'IL', 0, False],
 'BRCA1': [5, 'BR', 0, False],
 'LAMB3': [5, 'LA', 0, False],
 'HDAC1': [5, 'HD', 0, False]}

In [17]:
df = pd.DataFrame(lista_final)
df

  TNF-alpha   IL-6  BRCA1  LAMB3  HDAC1
0         9      4      5      5      5
1        TN     IL     BR     LA     HD
2         2      0      0      0      0
3     False  False  False  False  False

In [18]:
df.index = ["caracteres", "dois_primeiros", "contagem_a", "tem_hu"]
df

               TNF-alpha   IL-6  BRCA1  LAMB3  HDAC1
caracteres             9      4      5      5      5
dois_primeiros        TN     IL     BR     LA     HD
contagem_a             2      0      0      0      0
tem_hu             False  False  False  False  False

In [19]:
df.T

          caracteres dois_primeiros contagem_a tem_hu
TNF-alpha          9             TN          2  False
IL-6               4             IL          0  False
BRCA1              5             BR          0  False
LAMB3              5             LA          0  False
HDAC1              5             HD          0  False

In [68]:
df_genes = df.T

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [112]:
print(df_genes.iloc[:, [0, 2]])

          caracteres contagem_a
TNF-alpha          9          2
IL-6               4          0
BRCA1              5          0
LAMB3              5          0
HDAC1              5          0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [114]:
print(df_genes.iloc[[0, 2], [-1]])

          tem_hu
TNF-alpha  False
BRCA1      False

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [118]:
df_tabela = pd.read_csv("data.csv")
df_tabela

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [149]:
#Numero de entradas
entradas = df_tabela.shape[0]
entradas

36634

In [124]:
#Lista com as classes das colunas
classes_colunas = list(df_tabela.dtypes)
classes_colunas

[dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('int64')]

In [131]:
#Lista com o nº de elementos de cada classe
classes_elementos = df_tabela.dtypes.value_counts()
classes_elementos

float64    11
object      4
int64       3
Name: count, dtype: int64

In [132]:
classes_elementos = list(df_tabela.dtypes.value_counts())
classes_elementos

[11, 4, 3]

In [139]:
#Lista média da primeira, quarta e nona coluna
media = df_tabela.iloc[:, [0, 3, 8]]
media = media.mean(axis=1)
media

0        4.702816e+05
1        1.069545e+06
2        1.966981e+05
3        1.401992e+05
4        1.395595e+05
             ...
36629    1.864582e+05
36630    1.113478e+06
36631    3.900080e+05
36632    1.197064e+06
36633    4.558803e+05
Length: 36634, dtype: float64

In [141]:
media = list(df_tabela.iloc[:, [0, 3, 8]].mean(axis=1))
media

[470281.6333333333,
 1069544.6233333333,
 196698.06000000003,
 140199.16,
 139559.49666666667,
 556564.7233333333,
 7201977.333333333,
 300120.75,
 338111.19,
 619504.52,
 734368.5933333334,
 309624.73,
 163196.46333333335,
 208515.99666666667,
 297785.60000000003,
 314079.3566666667,
 215694.96666666667,
 180856.68000000002,
 280553.5,
 138496.43,
 136847.24666666667,
 4123797.3333333335,
 957338.2533333333,
 398164.8566666667,
 363795.38666666666,
 134299.90666666665,
 272696.81,
 271618.29333333333,
 211441.72666666668,
 94342.46,
 237420.47,
 268231.2866666667,
 286652.0633333333,
 248746.72333333336,
 316179.74,
 121126.59333333334,
 141079.29666666666,
 313979.43,
 1317728.7,
 166878.01666666666,
 275032.5733333333,
 278470.1933333333,
 88829.93,
 421284.7266666666,
 284930.11333333334,
 132020.67666666667,
 192894.17,
 119411.62,
 334126.62,
 118598.86333333334,
 179072.70666666667,
 253825.55333333332,
 307253.93333333335,
 272713.91333333333,
 166332.93333333332,
 324642.55,
 288803.1933333333,
 385192.36333333334,
 151919.94999999998,
 189090.33333333334,
 362891.99,
 517473.36999999994,
 386243.85333333333,
 414122.8433333333,
 273947.2033333333,
 117071.71,
 1883761.9633333336,
 128102.69,
 531605.0766666667,
 306669.52,
 123337.5,
 268542.66333333333,
 284510.5733333333,
 430247.2166666666,
 415896.3633333333,
 664156.8066666666,
 196577.69999999998,
 278462.48666666663,
 225315.25333333333,
 332253.79,
 451930.48666666663,
 299958.37,
 140472.46,
 293885.87333333335,
 194831.43000000002,
 131738.29666666666,
 150546.82666666666,
 103222.28666666667,
 217650.20666666667,
 95649.83,
 372760.92,
 353616.08666666667,
 653997.53,
 312577.36666666664,
 1116805.21,
 697566.4333333333,
 1161230.33,
 271967.63,
 457215.9033333333,
 987232.7666666666,
 343542.52999999997,
 602305.86,
 86988.61,
 435561.74666666664,
 130385.46999999999,
 185046.5,
 2602133.8833333333,
 219186.97999999998,
 353483.42,
 81310.21333333333,
 896746.1433333332,
 97158.2,
 754759.9266666668,
 2437867.966666667,
 104842.02999999998,
 217025.39,
 329265.60000000003,
 233547.07666666666,
 333990.55,
 151993.59,
 203566.69999999998,
 323525.52,
 311764.95666666667,
 343713.37,
 343389.13333333336,
 135821.35666666666,
 193463.31333333332,
 60284.67333333334,
 275440.5233333334,
 517225.4733333333,
 375107.2733333334,
 571894.3266666667,
 252601.29,
 244147.21333333335,
 197937.32333333333,
 288875.1766666667,
 328473.68333333335,
 215378.11,
 135510.03333333333,
 262713.06,
 138899.23666666666,
 267440.38,
 117038.97333333333,
 393776.76666666666,
 223967.12,
 64996.23,
 56621.573333333334,
 47947.386666666665,
 283349.01333333337,
 269730.95666666667,
 292471.20666666667,
 264358.5966666667,
 385267.9166666667,
 372734.25333333336,
 162104.26333333334,
 200446.53,
 415403.95,
 2891448.56,
 519581.7033333333,
 360098.07,
 495234.5933333333,
 422014.53,
 188453.92,
 147651.64666666667,
 277844.37666666665,
 540228.9266666666,
 3773367.3333333335,
 602683.3066666666,
 244592.9,
 261641.94999999998,
 383867.25666666665,
 902988.85,
 495189.38999999996,
 328312.17333333334,
 211460.30999999997,
 291649.95,
 266614.7166666667,
 262642.01666666666,
 198156.71,
 134993.65666666665,
 310538.51666666666,
 236948.56999999998,
 138645.86,
 268691.96,
 281782.32666666666,
 382569.0366666666,
 327197.2033333333,
 199467.60333333336,
 166793.97,
 436457.3133333333,
 243078.66666666666,
 274912.79,
 377188.4566666667,
 170571.34,
 117944.96,
 277069.82,
 260862.74333333332,
 337777.44333333336,
 3167223.66,
 4202427.666666667,
 263615.97,
 128778.33333333333,
 1446338.17,
 133212.80666666667,
 241794.10333333336,
 7028421.333333333,
 644478.1466666666,
 316023.82,
 136794.91333333333,
 271063.98666666663,
 186819.43666666668,
 209661.7333333333,
 415886.8,
 235114.95333333334,
 301982.3066666667,
 268821.3333333333,
 200687.70666666667,
 115357.37333333334,
 249155.30000000002,
 59522.68,
 798417.8666666667,
 257364.33,
 280316.1433333333,
 667520.2133333333,
 726181.29,
 315276.47000000003,
 329095.5533333333,
 238484.70666666667,
 314110.3433333333,
 420020.0466666667,
 377963.44,
 231352.55333333332,
 451424.35333333333,
 363831.3566666667,
 384773.62666666665,
 196099.04333333333,
 317194.39,
 214485.80666666667,
 1109833.8033333335,
 81675.74,
 461908.4033333333,
 163995.85,
 149506.46333333335,
 201756.99666666667,
 621367.5566666666,
 164081.26,
 357709.0933333333,
 450812.83666666667,
 336234.31666666665,
 318645.2966666667,
 297233.89,
 107275.26000000001,
 221781.33333333334,
 60244.52,
 62982.50666666666,
 112989.84333333334,
 84447.33333333333,
 238173.57333333333,
 214161.54,
 146144.05000000002,
 92972.77666666667,
 273861.13666666666,
 84289.73,
 188836.26333333334,
 320704.4066666667,
 195245.81000000003,
 185232.99333333332,
 296874.9733333333,
 198001.66,
 282073.14,
 274348.0266666667,
 230858.67333333334,
 244997.54,
 131482.38999999998,
 237124.56000000003,
 212694.39,
 225711.60666666666,
 160149.97333333333,
 196989.6133333333,
 216264.3633333333,
 100584.91666666667,
 277658.25666666665,
 80449.98,
 419135.84,
 270434.35333333333,
 45094.79,
 202762.20333333334,
 178907.79,
 264939.59,
 147803.97333333333,
 373511.2,
 132532.31,
 300652.68,
 92440.34999999999,
 183549.41,
 159089.23333333334,
 48310.556666666664,
 297038.8333333333,
 180580.09333333335,
 344881.10333333333,
 77036.39666666667,
 57695.71,
 305151.92333333334,
 256814.43999999997,
 147059.57,
 96278.66666666667,
 259801.69999999998,
 319060.51666666666,
 342852.0566666667,
 198841.68999999997,
 252856.1133333333,
 248432.79,
 117004.55333333334,
 506321.61000000004,
 493958.05666666664,
 486207.3566666667,
 475206.4733333333,
 1295587.3766666667,
 2512426.9366666665,
 381377.25333333336,
 526745.8566666666,
 326899.45666666667,
 250707.36666666667,
 156506.52666666667,
 460435.20999999996,
 118596.38666666667,
 625679.9066666666,
 273832.79,
 142597.33666666667,
 297851.3,
 462701.1333333333,
 282570.73,
 290657.11333333334,
 1408348.5066666666,
 332608.17333333334,
 155417.53666666665,
 287898.93333333335,
 132405.88,
 283647.66,
 1086131.7366666666,
 136460.31999999998,
 247683.83666666667,
 352205.62333333335,
 248080.17666666667,
 249124.43333333335,
 209360.87666666668,
 178923.43333333335,
 317188.1866666667,
 426596.58666666667,
 229969.09,
 104715.87333333334,
 252009.69333333333,
 78823.90999999999,
 247471.83,
 170485.95666666667,
 199427.99,
 458459.1099999999,
 706295.1566666666,
 1430822.7700000003,
 160100.50666666668,
 169246.56333333332,
 86924.24666666666,
 176124.67666666667,
 278930.95,
 258821.79666666666,
 2089218.4400000002,
 328637.18,
 93609.43333333333,
 675393.0566666666,
 47663.72,
 346687.3233333333,
 160156.80666666667,
 134253.77333333335,
 101471.88,
 41914.44666666666,
 60306.97666666666,
 241927.54333333333,
 350892.57,
 192154.32333333333,
 248435.56999999998,
 361742.4066666667,
 690977.63,
 332969.29,
 111935.58333333333,
 202245.44999999998,
 151111.54333333333,
 88200.79,
 189663.18666666668,
 383233.8233333333,
 148698.35666666666,
 254494.68333333335,
 431819.52,
 277689.29,
 341399.05333333334,
 117392.89000000001,
 289522.9733333333,
 280136.1933333333,
 235704.77666666664,
 550799.3533333334,
 448648.2833333334,
 328335.2166666667,
 198127.79333333333,
 163868.54,
 573661.9866666667,
 444861.72,
 243083.36666666667,
 194879.1133333333,
 332130.35000000003,
 835474.5533333333,
 458357.19333333336,
 364463.6533333333,
 259378.37666666668,
 734752.2666666666,
 40335987.333333336,
 182118.87666666668,
 279925.33666666667,
 212320.00333333333,
 219135.08,
 1650599.8099999998,
 417825.13000000006,
 605224.18,
 243782.2666666667,
 145188.28,
 162917.80333333332,
 162853.74,
 304550.69666666666,
 221664.83,
 196500.47666666665,
 363038.23666666663,
 350668.73666666663,
 151621.25,
 260295.78,
 216307.9,
 351516.2933333333,
 957618.3466666667,
 344240.4433333333,
 298391.63666666666,
 339577.5366666667,
 181977.80333333334,
 352646.94333333336,
 346568.52,
 99452.06333333334,
 148321.27,
 93727.36,
 60862.81333333333,
 284826.39333333337,
 257438.80333333334,
 203467.16666666666,
 258288.9,
 311430.87333333335,
 222812.84333333335,
 332511.24,
 313110.35333333333,
 40283.43,
 100345.11666666665,
 212436.84666666668,
 256766.22,
 249784.5166666667,
 265163.39666666667,
 215117.22,
 353810.30666666664,
 257929.72333333336,
 324695.04333333333,
 196265.12,
 61038.15666666667,
 50113.799999999996,
 134886.90666666665,
 93451.79333333333,
 197051.83333333334,
 502782.33666666667,
 373406.8566666667,
 269178.8466666667,
 3265537.6666666665,
 883679.0733333332,
 676230.67,
 478963.22000000003,
 517033.95333333337,
 390927.0366666666,
 394593.52999999997,
 221072.33666666667,
 288187.01666666666,
 408290.61000000004,
 296209.64666666667,
 146284.88999999998,
 171670.34,
 157050.51666666666,
 376814.9533333333,
 233195.61,
 212217.43333333335,
 741355.7799999999,
 303385.8233333333,
 260681.56999999998,
 364247.81666666665,
 211193.28666666665,
 1573333.9799999997,
 65476.85666666667,
 81825.67666666667,
 156161.25666666668,
 661931.9533333334,
 183202.09333333335,
 194190.18333333335,
 186697.16,
 208104.93333333335,
 306712.9633333333,
 322427.13333333336,
 188298.69333333333,
 98571.40666666666,
 296275.86666666664,
 134120.83,
 208402.56999999998,
 224221.75333333333,
 305075.8433333333,
 213908.54,
 299138.61,
 327737.48,
 51765.869999999995,
 290053.68,
 230319.55000000002,
 327724.88333333336,
 142862.50333333333,
 62707.21666666667,
 104842.04333333333,
 119697.41333333333,
 410776.92333333334,
 332033.13333333336,
 282437.11,
 384469.8666666667,
 182675.18999999997,
 200174.02000000002,
 294946.92,
 323024.99666666664,
 216623.5,
 267084.72000000003,
 302831.4166666667,
 60881.04,
 221396.61666666667,
 79075.08333333333,
 103355.30333333333,
 348773.79,
 270489.32,
 203046.71333333335,
 519482.6533333333,
 150785.58,
 411633.7766666667,
 297969.5933333333,
 303325.18,
 128856.16666666667,
 1934425.3666666665,
 277534.5266666667,
 283634.73,
 86714.88,
 312896.76666666666,
 462125.76,
 60540.22333333333,
 626743.8366666667,
 1072926.8966666667,
 272604.38333333336,
 77776.19,
 61096.4,
 199154.53666666665,
 132808.14666666667,
 154272.62333333332,
 13772878.333333334,
 2353341.32,
 5119210.303333334,
 264429.25333333336,
 290380.23333333334,
 217091.58666666667,
 321849.6066666667,
 357415.0366666666,
 154464.31666666668,
 121133.70333333332,
 2330156.43,
 391716.18,
 1100497.4266666668,
 2685085.2600000002,
 1673954.8566666667,
 1255778.6733333333,
 550399.17,
 167878.77,
 376742.62999999995,
 353148.53,
 185734.75333333333,
 234320.70333333334,
 397625.01,
 576585.41,
 941189.8133333334,
 237132.68666666668,
 140074.55333333334,
 119026.87,
 324704.9733333333,
 213635.03,
 884136.94,
 156029.75,
 54268.293333333335,
 359621.0533333333,
 2110017.3800000004,
 307737.11666666664,
 293144.42333333334,
 251097.72333333336,
 253692.53,
 148195.55666666667,
 274213.04333333333,
 665367.6233333334,
 228173.62666666668,
 122629.71666666667,
 116845.27333333333,
 228328.65,
 170782.63333333333,
 136192.38,
 73304.51333333334,
 590902.02,
 685443.4066666666,
 132317.87666666668,
 671587.7833333333,
 198509.16333333333,
 248435.57333333333,
 115322.56666666667,
 1383308.6666666667,
 421223.13999999996,
 606866.11,
 233546.51333333334,
 288719.76666666666,
 417283.97666666674,
 191296.19000000003,
 299777.14,
 73250.34333333334,
 313162.1866666667,
 178799.06999999998,
 90795.35333333333,
 928274.7366666667,
 81389.35666666667,
 305197.47000000003,
 797393.2933333333,
 285692.8466666667,
 4351885.333333333,
 914593.7833333333,
 183458.86000000002,
 218719.81666666665,
 380511.22,
 242862.49666666667,
 223369.72999999998,
 348798.2766666667,
 325034.64333333337,
 308523.8133333333,
 323086.87,
 273240.0733333333,
 305440.5933333333,
 130322.90999999999,
 329905.37333333335,
 334865.12333333335,
 99800.07666666666,
 398301.49666666664,
 299789.21,
 168732.33,
 265790.9433333333,
 149328.76,
 228019.28333333333,
 320250.36333333334,
 252011.57333333333,
 365541.8,
 283019.5966666667,
 1098374.8333333333,
 778087.4700000001,
 4249207.333333333,
 310165.43333333335,
 343560.73,
 317215.72,
 84056.81666666667,
 73269.31999999999,
 190023.43333333335,
 189204.59333333335,
 820319.0266666667,
 373534.9366666667,
 493943.9366666667,
 277455.19666666666,
 88095.90000000001,
 226065.43333333335,
 341318.29,
 108369.02,
 224248.1,
 176028.07666666666,
 319501.60000000003,
 133980.45333333334,
 138367.66666666666,
 315592.5566666667,
 272189.33666666667,
 262815.88333333336,
 308533.83,
 165135.42,
 276693.96,
 142199.67666666667,
 199252.41666666666,
 175746.60333333336,
 193414.31999999998,
 57687.613333333335,
 213905.52333333332,
 156397.83666666667,
 125509.21666666667,
 251440.49666666667,
 7722686.0,
 541912.9500000001,
 274884.7166666667,
 153570.47333333336,
 1105397.2033333334,
 331931.28,
 113846.90000000001,
 222424.84,
 224119.85,
 218153.7333333333,
 246129.46,
 332275.48,
 170348.63333333333,
 351090.01,
 190935.91666666666,
 102919.67,
 98283.90666666666,
 270972.4433333333,
 152931.34666666665,
 51271.943333333336,
 59645.693333333336,
 1556897.6166666665,
 407503.51,
 269883.5233333333,
 139080.84,
 130942.69333333334,
 393777.48,
 64838.176666666666,
 176014.65333333332,
 134378.68333333332,
 271366.2266666667,
 179257.37666666668,
 61853.99333333334,
 565890.5866666667,
 227282.77000000002,
 687956.1566666666,
 289898.76333333337,
 644009.83,
 306343.9066666667,
 244269.31000000003,
 206670.15333333332,
 248266.58666666667,
 181273.71666666667,
 222332.11666666667,
 239003.30000000002,
 55619.200000000004,
 290068.82,
 264661.74333333335,
 175606.22,
 76761.39666666667,
 115778.34999999999,
 78856.22,
 331594.32666666666,
 121410.74333333333,
 534166.6633333333,
 533833.5,
 459760.26666666666,
 869385.7600000001,
 247332.92666666667,
 192022.30333333334,
 246177.70333333334,
 159434.51,
 63988.26,
 285374.11333333334,
 111980.48333333334,
 150787.99,
 59182.30666666667,
 147130.90666666665,
 294908.01666666666,
 221070.81333333332,
 46502.85333333333,
 205602.08333333334,
 292415.7166666667,
 133788.1,
 183196.71,
 81452.17,
 603722.35,
 1278249.9166666667,
 586623.9266666666,
 428394.63000000006,
 946676.2399999999,
 591160.6366666667,
 148396.76333333334,
 55898.34666666667,
 268183.38,
 288752.22000000003,
 335290.3066666667,
 186285.54666666666,
 46531.4,
 315158.2833333333,
 337717.98,
 75492.13666666667,
 229874.87,
 56445.64666666667,
 323008.17333333334,
 268622.4733333333,
 91909.52,
 343315.43,
 164327.07,
 73543.32333333333,
 373028.7833333334,
 537410.0166666667,
 521771.5633333333,
 233862.6366666667,
 323023.14999999997,
 198971.60666666666,
 224994.47999999998,
 508612.5733333333,
 604411.9733333333,
 605229.3166666667,
 607246.5233333333,
 185022.0166666667,
 535486.1433333333,
 431924.14999999997,
 582648.64,
 505452.12000000005,
 1505566.8499999999,
 343030.9533333333,
 150598.0,
 161084.51333333334,
 105792.94,
 260913.08,
 1165832.5733333335,
 1432237.7033333331,
 251627.71666666667,
 116921.04333333333,
 87987.49666666666,
 131372.96,
 127201.93,
 756819.2533333333,
 155048.59666666665,
 492662.52,
 259838.09666666668,
 202162.3633333333,
 123240.12333333334,
 1249645.24,
 173546.53666666665,
 1231911.7866666666,
 345585.0633333333,
 545533.8766666666,
 278452.62666666665,
 338090.04,
 413313.5466666667,
 361925.55,
 206400.54,
 445905.74666666664,
 453113.56000000006,
 314797.76,
 380943.57,
 165824.52,
 1386327.9766666666,
 754962.14,
 433653.2066666667,
 307145.4366666667,
 197309.80666666667,
 150751.40666666665,
 66004.99333333333,
 441120.06000000006,
 539026.6766666666,
 285610.74666666664,
 449886.6566666667,
 6563182.0,
 524745.5066666667,
 5219571.333333333,
 1605514.42,
 158871.20333333334,
 330999.01,
 141043.15,
 322320.24666666664,
 291781.07,
 359883.0233333334,
 369480.3666666667,
 342235.4666666667,
 318075.3233333333,
 66585.89,
 254635.09333333335,
 205198.05666666667,
 106745.31,
 186921.77333333332,
 128228.68666666666,
 303456.33,
 514865.6166666667,
 279314.2233333333,
 269763.06,
 375179.9733333333,
 323109.75,
 315761.43,
 422192.3433333333,
 413887.12333333335,
 143092.44666666666,
 211743.83666666667,
 325625.41,
 252549.37333333332,
 805622.2599999999,
 275676.36666666664,
 205367.69666666666,
 313113.7966666667,
 244306.72333333336,
 549162.8333333334,
 356998.20333333337,
 476058.51,
 2284756.9766666666,
 240939.78,
 294614.97000000003,
 481590.47000000003,
 538102.0499999999,
 959928.75,
 55059.00666666666,
 206893.1,
 190926.6433333333,
 63185.69,
 153414.9,
 285996.51666666666,
 295430.2,
 222684.44333333333,
 716100.0133333333,
 218510.36666666667,
 108452.55666666666,
 305890.33,
 274156.8466666667,
 590869.0166666667,
 650520.99,
 4386576.666666667,
 516798.3666666667,
 1642551.96,
 286672.3,
 355094.25,
 240824.43333333335,
 1573947.5033333332,
 155012.21,
 162324.77333333335,
 232429.37,
 173672.30333333332,
 451442.6866666667,
 710486.1733333333,
 302312.16333333333,
 6402028.666666667,
 102716.70333333332,
 269246.49666666664,
 134911.62666666668,
 102905.46666666667,
 347493.9366666667,
 325601.88,
 103562.20333333332,
 185188.53,
 310789.67,
 76195.76666666666,
 213105.67333333334,
 218818.03333333333,
 160382.63333333333,
 195270.20666666667,
 302795.10333333333,
 488149.3466666667,
 515923.69333333336,
 465755.92,
 517171.02,
 386793.54000000004,
 326245.87,
 259059.13,
 360551.43333333335,
 255013.30666666667,
 7421329.0,
 12585171.333333334,
 858611.0033333333,
 334217.2766666667,
 153686.93333333332,
 213755.16,
 281030.14666666667,
 207074.21666666667,
 101986.07666666666,
 97819.45333333332,
 190379.44666666666,
 309103.10333333333,
 237548.93333333335,
 300212.35000000003,
 705967.0766666667,
 308203.7966666667,
 328296.27999999997,
 319166.49666666664,
 107186.02,
 596757.4066666666,
 269137.87,
 415034.1566666667,
 2240684.0633333335,
 548459.24,
 266798.59,
 235905.84,
 137559.31,
 319304.37333333335,
 221264.30333333332,
 198858.70666666667,
 151341.13,
 193689.12666666668,
 271284.41,
 221847.78333333333,
 150613.07666666666,
 293358.8466666667,
 103937.94666666667,
 242349.53333333333,
 241035.56666666665,
 ...]

In [144]:
#Lista desvio padrão
desvio_padrao = list(df_tabela.iloc[:, [0, 3, 8]].std(axis=0))
desvio_padrao

[259912.9264939009, 17523003.588415086, 20367766.569178067]

In [145]:
#Lista com o terceiro quartil da primeira, quarta e nona colunas
quartil = list(df_tabela.iloc[:, [0, 3, 8]].quantile(0.75))
quartil

[774252.0, 0.0, 1128871.1824999999]

In [147]:
#Dicionário 
dicionario_tabela = {
    "entradas": entradas,
    "classes_colunas": classes_colunas,
    "classes_elementos": classes_elementos,
    "media": media,
    "desvio_padrao": desvio_padrao,
    "quartil": quartil
}
dicionario_tabela

{'entradas': 36634,
 'classes_colunas': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'classes_elementos': [11, 4, 3],
 'media': [470281.6333333333,
  1069544.6233333333,
  196698.06000000003,
  140199.16,
  139559.49666666667,
  556564.7233333333,
  7201977.333333333,
  300120.75,
  338111.19,
  619504.52,
  734368.5933333334,
  309624.73,
  163196.46333333335,
  208515.99666666667,
  297785.60000000003,
  314079.3566666667,
  215694.96666666667,
  180856.68000000002,
  280553.5,
  138496.43,
  136847.24666666667,
  4123797.3333333335,
  957338.2533333333,
  398164.8566666667,
  363795.38666666666,
  134299.90666666665,
  272696.81,
  271618.29333333333,
  211441.72666666668,
  94342.46,
  237420.47,
  268231.2866666667,
  286652.0633333333,
  248746.72333333336,
  316179.74,
  121126.59333333334,
  141079.29666666666,
  313979.43,
  1317728.7,
  166878.01666666666,
  275032.5733333333,
  278470.1933333333,
  88829.93,
  421284.7266666666,
  284930.11333333334,
  132020.67666666667,
  192894.17,
  119411.62,
  334126.62,
  118598.86333333334,
  179072.70666666667,
  253825.55333333332,
  307253.93333333335,
  272713.91333333333,
  166332.93333333332,
  324642.55,
  288803.1933333333,
  385192.36333333334,
  151919.94999999998,
  189090.33333333334,
  362891.99,
  517473.36999999994,
  386243.85333333333,
  414122.8433333333,
  273947.2033333333,
  117071.71,
  1883761.9633333336,
  128102.69,
  531605.0766666667,
  306669.52,
  123337.5,
  268542.66333333333,
  284510.5733333333,
  430247.2166666666,
  415896.3633333333,
  664156.8066666666,
  196577.69999999998,
  278462.48666666663,
  225315.25333333333,
  332253.79,
  451930.48666666663,
  299958.37,
  140472.46,
  293885.87333333335,
  194831.43000000002,
  131738.29666666666,
  150546.82666666666,
  103222.28666666667,
  217650.20666666667,
  95649.83,
  372760.92,
  353616.08666666667,
  653997.53,
  312577.36666666664,
  1116805.21,
  697566.4333333333,
  1161230.33,
  271967.63,
  457215.9033333333,
  987232.7666666666,
  343542.52999999997,
  602305.86,
  86988.61,
  435561.74666666664,
  130385.46999999999,
  185046.5,
  2602133.8833333333,
  219186.97999999998,
  353483.42,
  81310.21333333333,
  896746.1433333332,
  97158.2,
  754759.9266666668,
  2437867.966666667,
  104842.02999999998,
  217025.39,
  329265.60000000003,
  233547.07666666666,
  333990.55,
  151993.59,
  203566.69999999998,
  323525.52,
  311764.95666666667,
  343713.37,
  343389.13333333336,
  135821.35666666666,
  193463.31333333332,
  60284.67333333334,
  275440.5233333334,
  517225.4733333333,
  375107.2733333334,
  571894.3266666667,
  252601.29,
  244147.21333333335,
  197937.32333333333,
  288875.1766666667,
  328473.68333333335,
  215378.11,
  135510.03333333333,
  262713.06,
  138899.23666666666,
  267440.38,
  117038.97333333333,
  393776.76666666666,
  223967.12,
  64996.23,
  56621.573333333334,
  47947.386666666665,
  283349.01333333337,
  269730.95666666667,
  292471.20666666667,
  264358.5966666667,
  385267.9166666667,
  372734.25333333336,
  162104.26333333334,
  200446.53,
  415403.95,
  2891448.56,
  519581.7033333333,
  360098.07,
  495234.5933333333,
  422014.53,
  188453.92,
  147651.64666666667,
  277844.37666666665,
  540228.9266666666,
  3773367.3333333335,
  602683.3066666666,
  244592.9,
  261641.94999999998,
  383867.25666666665,
  902988.85,
  495189.38999999996,
  328312.17333333334,
  211460.30999999997,
  291649.95,
  266614.7166666667,
  262642.01666666666,
  198156.71,
  134993.65666666665,
  310538.51666666666,
  236948.56999999998,
  138645.86,
  268691.96,
  281782.32666666666,
  382569.0366666666,
  327197.2033333333,
  199467.60333333336,
  166793.97,
  436457.3133333333,
  243078.66666666666,
  274912.79,
  377188.4566666667,
  170571.34,
  117944.96,
  277069.82,
  260862.74333333332,
  337777.44333333336,
  3167223.66,
  4202427.666666667,
  263615.97,
  128778.33333333333,
  1446338.17,
  133212.80666666667,
  241794.10333333336,
  7028421.333333333,
  644478.1466666666,
  316023.82,
  136794.91333333333,
  271063.98666666663,
  186819.43666666668,
  209661.7333333333,
  415886.8,
  235114.95333333334,
  301982.3066666667,
  268821.3333333333,
  200687.70666666667,
  115357.37333333334,
  249155.30000000002,
  59522.68,
  798417.8666666667,
  257364.33,
  280316.1433333333,
  667520.2133333333,
  726181.29,
  315276.47000000003,
  329095.5533333333,
  238484.70666666667,
  314110.3433333333,
  420020.0466666667,
  377963.44,
  231352.55333333332,
  451424.35333333333,
  363831.3566666667,
  384773.62666666665,
  196099.04333333333,
  317194.39,
  214485.80666666667,
  1109833.8033333335,
  81675.74,
  461908.4033333333,
  163995.85,
  149506.46333333335,
  201756.99666666667,
  621367.5566666666,
  164081.26,
  357709.0933333333,
  450812.83666666667,
  336234.31666666665,
  318645.2966666667,
  297233.89,
  107275.26000000001,
  221781.33333333334,
  60244.52,
  62982.50666666666,
  112989.84333333334,
  84447.33333333333,
  238173.57333333333,
  214161.54,
  146144.05000000002,
  92972.77666666667,
  273861.13666666666,
  84289.73,
  188836.26333333334,
  320704.4066666667,
  195245.81000000003,
  185232.99333333332,
  296874.9733333333,
  198001.66,
  282073.14,
  274348.0266666667,
  230858.67333333334,
  244997.54,
  131482.38999999998,
  237124.56000000003,
  212694.39,
  225711.60666666666,
  160149.97333333333,
  196989.6133333333,
  216264.3633333333,
  100584.91666666667,
  277658.25666666665,
  80449.98,
  419135.84,
  270434.35333333333,
  45094.79,
  202762.20333333334,
  178907.79,
  264939.59,
  147803.97333333333,
  373511.2,
  132532.31,
  300652.68,
  92440.34999999999,
  183549.41,
  159089.23333333334,
  48310.556666666664,
  297038.8333333333,
  180580.09333333335,
  344881.10333333333,
  77036.39666666667,
  57695.71,
  305151.92333333334,
  256814.43999999997,
  147059.57,
  96278.66666666667,
  259801.69999999998,
  319060.51666666666,
  342852.0566666667,
  198841.68999999997,
  252856.1133333333,
  248432.79,
  117004.55333333334,
  506321.61000000004,
  493958.05666666664,
  486207.3566666667,
  475206.4733333333,
  1295587.3766666667,
  2512426.9366666665,
  381377.25333333336,
  526745.8566666666,
  326899.45666666667,
  250707.36666666667,
  156506.52666666667,
  460435.20999999996,
  118596.38666666667,
  625679.9066666666,
  273832.79,
  142597.33666666667,
  297851.3,
  462701.1333333333,
  282570.73,
  290657.11333333334,
  1408348.5066666666,
  332608.17333333334,
  155417.53666666665,
  287898.93333333335,
  132405.88,
  283647.66,
  1086131.7366666666,
  136460.31999999998,
  247683.83666666667,
  352205.62333333335,
  248080.17666666667,
  249124.43333333335,
  209360.87666666668,
  178923.43333333335,
  317188.1866666667,
  426596.58666666667,
  229969.09,
  104715.87333333334,
  252009.69333333333,
  78823.90999999999,
  247471.83,
  170485.95666666667,
  199427.99,
  458459.1099999999,
  706295.1566666666,
  1430822.7700000003,
  160100.50666666668,
  169246.56333333332,
  86924.24666666666,
  176124.67666666667,
  278930.95,
  258821.79666666666,
  2089218.4400000002,
  328637.18,
  93609.43333333333,
  675393.0566666666,
  47663.72,
  346687.3233333333,
  160156.80666666667,
  134253.77333333335,
  101471.88,
  41914.44666666666,
  60306.97666666666,
  241927.54333333333,
  350892.57,
  192154.32333333333,
  248435.56999999998,
  361742.4066666667,
  690977.63,
  332969.29,
  111935.58333333333,
  202245.44999999998,
  151111.54333333333,
  88200.79,
  189663.18666666668,
  383233.8233333333,
  148698.35666666666,
  254494.68333333335,
  431819.52,
  277689.29,
  341399.05333333334,
  117392.89000000001,
  289522.9733333333,
  280136.1933333333,
  235704.77666666664,
  550799.3533333334,
  448648.2833333334,
  328335.2166666667,
  198127.79333333333,
  163868.54,
  573661.9866666667,
  444861.72,
  243083.36666666667,
  194879.1133333333,
  332130.35000000003,
  835474.5533333333,
  458357.19333333336,
  364463.6533333333,
  259378.37666666668,
  734752.2666666666,
  40335987.333333336,
  182118.87666666668,
  279925.33666666667,
  212320.00333333333,
  219135.08,
  1650599.8099999998,
  417825.13000000006,
  605224.18,
  243782.2666666667,
  145188.28,
  162917.80333333332,
  162853.74,
  304550.69666666666,
  221664.83,
  196500.47666666665,
  363038.23666666663,
  350668.73666666663,
  151621.25,
  260295.78,
  216307.9,
  351516.2933333333,
  957618.3466666667,
  344240.4433333333,
  298391.63666666666,
  339577.5366666667,
  181977.80333333334,
  352646.94333333336,
  346568.52,
  99452.06333333334,
  148321.27,
  93727.36,
  60862.81333333333,
  284826.39333333337,
  257438.80333333334,
  203467.16666666666,
  258288.9,
  311430.87333333335,
  222812.84333333335,
  332511.24,
  313110.35333333333,
  40283.43,
  100345.11666666665,
  212436.84666666668,
  256766.22,
  249784.5166666667,
  265163.39666666667,
  215117.22,
  353810.30666666664,
  257929.72333333336,
  324695.04333333333,
  196265.12,
  61038.15666666667,
  50113.799999999996,
  134886.90666666665,
  93451.79333333333,
  197051.83333333334,
  502782.33666666667,
  373406.8566666667,
  269178.8466666667,
  3265537.6666666665,
  883679.0733333332,
  676230.67,
  478963.22000000003,
  517033.95333333337,
  390927.0366666666,
  394593.52999999997,
  221072.33666666667,
  288187.01666666666,
  408290.61000000004,
  296209.64666666667,
  146284.88999999998,
  171670.34,
  157050.51666666666,
  376814.9533333333,
  233195.61,
  212217.43333333335,
  741355.7799999999,
  303385.8233333333,
  260681.56999999998,
  364247.81666666665,
  211193.28666666665,
  1573333.9799999997,
  65476.85666666667,
  81825.67666666667,
  156161.25666666668,
  661931.9533333334,
  183202.09333333335,
  194190.18333333335,
  186697.16,
  208104.93333333335,
  306712.9633333333,
  322427.13333333336,
  188298.69333333333,
  98571.40666666666,
  296275.86666666664,
  134120.83,
  208402.56999999998,
  224221.75333333333,
  305075.8433333333,
  213908.54,
  299138.61,
  327737.48,
  51765.869999999995,
  290053.68,
  230319.55000000002,
  327724.88333333336,
  142862.50333333333,
  62707.21666666667,
  104842.04333333333,
  119697.41333333333,
  410776.92333333334,
  332033.13333333336,
  282437.11,
  384469.8666666667,
  182675.18999999997,
  200174.02000000002,
  294946.92,
  323024.99666666664,
  216623.5,
  267084.72000000003,
  302831.4166666667,
  60881.04,
  221396.61666666667,
  79075.08333333333,
  103355.30333333333,
  348773.79,
  270489.32,
  203046.71333333335,
  519482.6533333333,
  150785.58,
  411633.7766666667,
  297969.5933333333,
  303325.18,
  128856.16666666667,
  1934425.3666666665,
  277534.5266666667,
  283634.73,
  86714.88,
  312896.76666666666,
  462125.76,
  60540.22333333333,
  626743.8366666667,
  1072926.8966666667,
  272604.38333333336,
  77776.19,
  61096.4,
  199154.53666666665,
  132808.14666666667,
  154272.62333333332,
  13772878.333333334,
  2353341.32,
  5119210.303333334,
  264429.25333333336,
  290380.23333333334,
  217091.58666666667,
  321849.6066666667,
  357415.0366666666,
  154464.31666666668,
  121133.70333333332,
  2330156.43,
  391716.18,
  1100497.4266666668,
  2685085.2600000002,
  1673954.8566666667,
  1255778.6733333333,
  550399.17,
  167878.77,
  376742.62999999995,
  353148.53,
  185734.75333333333,
  234320.70333333334,
  397625.01,
  576585.41,
  941189.8133333334,
  237132.68666666668,
  140074.55333333334,
  119026.87,
  324704.9733333333,
  213635.03,
  884136.94,
  156029.75,
  54268.293333333335,
  359621.0533333333,
  2110017.3800000004,
  307737.11666666664,
  293144.42333333334,
  251097.72333333336,
  253692.53,
  148195.55666666667,
  274213.04333333333,
  665367.6233333334,
  228173.62666666668,
  122629.71666666667,
  116845.27333333333,
  228328.65,
  170782.63333333333,
  136192.38,
  73304.51333333334,
  590902.02,
  685443.4066666666,
  132317.87666666668,
  671587.7833333333,
  198509.16333333333,
  248435.57333333333,
  115322.56666666667,
  1383308.6666666667,
  421223.13999999996,
  606866.11,
  233546.51333333334,
  288719.76666666666,
  417283.97666666674,
  191296.19000000003,
  299777.14,
  73250.34333333334,
  313162.1866666667,
  178799.06999999998,
  90795.35333333333,
  928274.7366666667,
  81389.35666666667,
  305197.47000000003,
  797393.2933333333,
  285692.8466666667,
  4351885.333333333,
  914593.7833333333,
  183458.86000000002,
  218719.81666666665,
  380511.22,
  242862.49666666667,
  223369.72999999998,
  348798.2766666667,
  325034.64333333337,
  308523.8133333333,
  323086.87,
  273240.0733333333,
  305440.5933333333,
  130322.90999999999,
  329905.37333333335,
  334865.12333333335,
  99800.07666666666,
  398301.49666666664,
  299789.21,
  168732.33,
  265790.9433333333,
  149328.76,
  228019.28333333333,
  320250.36333333334,
  252011.57333333333,
  365541.8,
  283019.5966666667,
  1098374.8333333333,
  778087.4700000001,
  4249207.333333333,
  310165.43333333335,
  343560.73,
  317215.72,
  84056.81666666667,
  73269.31999999999,
  190023.43333333335,
  189204.59333333335,
  820319.0266666667,
  373534.9366666667,
  493943.9366666667,
  277455.19666666666,
  88095.90000000001,
  226065.43333333335,
  341318.29,
  108369.02,
  224248.1,
  176028.07666666666,
  319501.60000000003,
  133980.45333333334,
  138367.66666666666,
  315592.5566666667,
  272189.33666666667,
  262815.88333333336,
  308533.83,
  165135.42,
  276693.96,
  142199.67666666667,
  199252.41666666666,
  175746.60333333336,
  193414.31999999998,
  57687.613333333335,
  213905.52333333332,
  156397.83666666667,
  125509.21666666667,
  251440.49666666667,
  7722686.0,
  541912.9500000001,
  274884.7166666667,
  153570.47333333336,
  1105397.2033333334,
  331931.28,
  113846.90000000001,
  222424.84,
  224119.85,
  218153.7333333333,
  246129.46,
  332275.48,
  170348.63333333333,
  351090.01,
  190935.91666666666,
  102919.67,
  98283.90666666666,
  270972.4433333333,
  152931.34666666665,
  51271.943333333336,
  59645.693333333336,
  1556897.6166666665,
  407503.51,
  269883.5233333333,
  139080.84,
  130942.69333333334,
  393777.48,
  64838.176666666666,
  176014.65333333332,
  134378.68333333332,
  271366.2266666667,
  179257.37666666668,
  61853.99333333334,
  565890.5866666667,
  227282.77000000002,
  687956.1566666666,
  289898.76333333337,
  644009.83,
  306343.9066666667,
  244269.31000000003,
  206670.15333333332,
  248266.58666666667,
  181273.71666666667,
  222332.11666666667,
  239003.30000000002,
  55619.200000000004,
  290068.82,
  264661.74333333335,
  175606.22,
  76761.39666666667,
  115778.34999999999,
  78856.22,
  331594.32666666666,
  121410.74333333333,
  534166.6633333333,
  533833.5,
  459760.26666666666,
  869385.7600000001,
  247332.92666666667,
  192022.30333333334,
  246177.70333333334,
  159434.51,
  63988.26,
  285374.11333333334,
  111980.48333333334,
  150787.99,
  59182.30666666667,
  147130.90666666665,
  294908.01666666666,
  221070.81333333332,
  46502.85333333333,
  205602.08333333334,
  292415.7166666667,
  133788.1,
  183196.71,
  81452.17,
  603722.35,
  1278249.9166666667,
  586623.9266666666,
  428394.63000000006,
  946676.2399999999,
  591160.6366666667,
  148396.76333333334,
  55898.34666666667,
  268183.38,
  288752.22000000003,
  335290.3066666667,
  186285.54666666666,
  46531.4,
  315158.2833333333,
  337717.98,
  75492.13666666667,
  229874.87,
  56445.64666666667,
  323008.17333333334,
  268622.4733333333,
  91909.52,
  343315.43,
  164327.07,
  73543.32333333333,
  373028.7833333334,
  537410.0166666667,
  521771.5633333333,
  233862.6366666667,
  323023.14999999997,
  198971.60666666666,
  224994.47999999998,
  508612.5733333333,
  604411.9733333333,
  605229.3166666667,
  607246.5233333333,
  185022.0166666667,
  535486.1433333333,
  431924.14999999997,
  582648.64,
  505452.12000000005,
  1505566.8499999999,
  343030.9533333333,
  150598.0,
  161084.51333333334,
  105792.94,
  260913.08,
  1165832.5733333335,
  1432237.7033333331,
  251627.71666666667,
  116921.04333333333,
  87987.49666666666,
  131372.96,
  127201.93,
  756819.2533333333,
  155048.59666666665,
  492662.52,
  259838.09666666668,
  202162.3633333333,
  123240.12333333334,
  1249645.24,
  173546.53666666665,
  1231911.7866666666,
  345585.0633333333,
  545533.8766666666,
  278452.62666666665,
  338090.04,
  413313.5466666667,
  361925.55,
  206400.54,
  445905.74666666664,
  453113.56000000006,
  314797.76,
  380943.57,
  165824.52,
  1386327.9766666666,
  754962.14,
  433653.2066666667,
  307145.4366666667,
  197309.80666666667,
  150751.40666666665,
  66004.99333333333,
  441120.06000000006,
  539026.6766666666,
  285610.74666666664,
  449886.6566666667,
  6563182.0,
  524745.5066666667,
  5219571.333333333,
  1605514.42,
  158871.20333333334,
  330999.01,
  141043.15,
  322320.24666666664,
  291781.07,
  359883.0233333334,
  369480.3666666667,
  342235.4666666667,
  318075.3233333333,
  66585.89,
  254635.09333333335,
  205198.05666666667,
  106745.31,
  186921.77333333332,
  128228.68666666666,
  303456.33,
  514865.6166666667,
  279314.2233333333,
  269763.06,
  375179.9733333333,
  323109.75,
  315761.43,
  422192.3433333333,
  413887.12333333335,
  143092.44666666666,
  211743.83666666667,
  325625.41,
  252549.37333333332,
  805622.2599999999,
  275676.36666666664,
  205367.69666666666,
  313113.7966666667,
  244306.72333333336,
  549162.8333333334,
  356998.20333333337,
  476058.51,
  2284756.9766666666,
  240939.78,
  294614.97000000003,
  481590.47000000003,
  538102.0499999999,
  959928.75,
  55059.00666666666,
  206893.1,
  190926.6433333333,
  63185.69,
  153414.9,
  285996.51666666666,
  295430.2,
  222684.44333333333,
  716100.0133333333,
  218510.36666666667,
  108452.55666666666,
  305890.33,
  274156.8466666667,
  590869.0166666667,
  650520.99,
  4386576.666666667,
  516798.3666666667,
  1642551.96,
  286672.3,
  355094.25,
  240824.43333333335,
  1573947.5033333332,
  155012.21,
  162324.77333333335,
  232429.37,
  173672.30333333332,
  451442.6866666667,
  710486.1733333333,
  302312.16333333333,
  6402028.666666667,
  102716.70333333332,
  269246.49666666664,
  134911.62666666668,
  102905.46666666667,
  347493.9366666667,
  325601.88,
  103562.20333333332,
  185188.53,
  310789.67,
  76195.76666666666,
  213105.67333333334,
  218818.03333333333,
  160382.63333333333,
  195270.20666666667,
  302795.10333333333,
  488149.3466666667,
  515923.69333333336,
  465755.92,
  517171.02,
  386793.54000000004,
  326245.87,
  259059.13,
  360551.43333333335,
  255013.30666666667,
  7421329.0,
  12585171.333333334,
  858611.0033333333,
  334217.2766666667,
  153686.93333333332,
  213755.16,
  281030.14666666667,
  207074.21666666667,
  101986.07666666666,
  97819.45333333332,
  190379.44666666666,
  309103.10333333333,
  237548.93333333335,
  300212.35000000003,
  705967.0766666667,
  308203.7966666667,
  328296.27999999997,
  319166.49666666664,
  107186.02,
  596757.4066666666,
  269137.87,
  415034.1566666667,
  2240684.0633333335,
  548459.24,
  266798.59,
  235905.84,
  137559.31,
  319304.37333333335,
  221264.30333333332,
  198858.70666666667,
  151341.13,
  193689.12666666668,
  271284.41,
  221847.78333333333,
  150613.07666666666,
  293358.8466666667,
  103937.94666666667,
  242349.53333333333,
  241035.56666666665,
  ...],
 'desvio_padrao': [259912.9264939009, 17523003.588415086, 20367766.569178067],
 'quartil': [774252.0, 0.0, 1128871.1824999999]}