# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [1]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

In [2]:
p and q and r and s and t

False

In [4]:
p and q and r or s or t

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [11]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ('a',1,True,'b',0,False) != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [12]:
p or q or r or s or t or u

True

In [20]:
not (p or q or r or s or t or u)

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [25]:
import pandas as pd

In [29]:
df_3 = pd.read_csv("df.csv", index_col = "Unnamed: 0").round(3)
df_3

          col1   col2    col3   col4  medias
linha1   2.600  2.800  34.730  0.070  10.050
linha2   0.140  1.612   1.673  5.893   2.330
linha3   0.265  0.374   2.600  2.800   1.510
linha4  34.730  0.070   0.140  1.612   9.138
linha5   1.673  5.893   0.265  0.374   2.051
medias   7.882  2.150   7.882  2.150   5.016

In [30]:
((df_3.loc["linha2"] == df_3.loc["linha3"]).all()) or ((df_3.loc["linha3"] == df_3.loc["linha4"]).all(  ))

np.False_

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [32]:
(df_3.loc ["linha1"] >= 10).all()

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [37]:
((df_3 ["col3"] >= 0) & (df_3 ["col3"] <= 40)).all()

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [38]:
(df_3.loc ["medias"] > 10).any()

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [39]:
df_3 [(df_3 >5) & (df_3 < 7)]

        col1   col2  col3   col4  medias
linha1   NaN    NaN   NaN    NaN     NaN
linha2   NaN    NaN   NaN  5.893     NaN
linha3   NaN    NaN   NaN    NaN     NaN
linha4   NaN    NaN   NaN    NaN     NaN
linha5   NaN  5.893   NaN    NaN     NaN
medias   NaN    NaN   NaN    NaN   5.016

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [40]:
df_3[(df_3 <= 5) | (df_3 >= 7)]

          col1   col2    col3   col4  medias
linha1   2.600  2.800  34.730  0.070  10.050
linha2   0.140  1.612   1.673    NaN   2.330
linha3   0.265  0.374   2.600  2.800   1.510
linha4  34.730  0.070   0.140  1.612   9.138
linha5   1.673    NaN   0.265  0.374   2.051
medias   7.882  2.150   7.882  2.150     NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [41]:
array_1 = df_3 ["col4"].to_numpy()
array_2 = df_3 ["medias"].to_numpy()

In [42]:
print(array_1)
print(array_2)

[0.07  5.893 2.8   1.612 0.374 2.15 ]
[10.05   2.33   1.51   9.138  2.051  5.016]

In [44]:
((array_1 >= 2) & (array_2 <= 5)).any()

np.True_

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [45]:
((array_1 > -1) & (array_1 <12)).all() and ((array_2 > -1) & (array_2 <12)).all()

np.True_